#!/bin/bash

# User editable
OSX_COMPUTER_NAME="calculon"
OSX_HOST_NAME="calculon"
OSX_HOME_DIR="/Volumes/Home/Users/mario"
USER_NAME="Mario Rogic"
USER_EMAIL="hello@mario.net.au"
GIT_REMOTE="git@github.com:supermario/fresh.git"

# Hard coded
COLOUR_PASS=$(tput setaf 2)
COLOUR_INFO=$(tput setaf 4)
COLOUR_WARN=$(tput setaf 3)
COLOUR_ERROR=$(tput setaf 1)
COLOUR_RESET=$(tput sgr0)

desired_brew_formulae=(
  # System
  'apple-gcc42'
  'coreutils'
  'modules'

  # Tooling
  'ack'
  'bash'
  'bash-completion'
  'curl'
  'direnv'
  'findutils'
  'git'
  'grep'
  'htop-osx'
  'hub'
  'lunchy'
  'ncdu' # shell based disk usage analyzer
  'nmap'
  'readline'
  'tmux'
  'tree'
  'vim'
  'wget'

  # Containers
  'docker'
  'boot2docker'

  # Libs
  'ffmpeg'
  'imagemagick'
  'libxml2'
  'libyaml'

  # Langs
  'rvm'
  'nvm'
  'haskell-stack'

  # Apps
  'brew-cask'
  'memcached'
  'phantomjs'
  'postgresql'
  'redis'
  'sqlite'
)

desired_casks=(
  'dropbox'
  'firefox'
  'google-chrome'
  'heroku-toolbelt'
  'istat-menus'
  'iterm2'
  'quicklook-json'
  'skype'
  'slack'
  'spotify'
  'sublime-text'
  'virtualbox'
  'transmission'
  'licecap' # Gif screencasts
  'private-internet-access'
)

desired_taps=(
  'caskroom/cask'
  'homebrew/versions'
  'homebrew/dupes'
)
